import createClient from "openapi-fetch";
import type { paths } from "./schema.d.ts"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://api-web.nhle.com/" });

async function playerSpotlight() {
    const results = await client.GET("/v1/player-spotlight");
    console.log(results);

};
